apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processor-deployment
  template:
    metadata:
      labels:
        app: image-processor-deployment
    spec:
      containers:
        - name: image-processor
          image: pavan1820/image-processor:v7
          env:
            - name: GCP_PROJECT
              value: "dcsc-project-440602"
            - name: GCP_BUCKET_NAME
              value: "cu-image-flow"
            - name: IMAGE_PUBSUB_TOPIC
              value: "projects/dcsc-project-440602/topics/image-processing-queue"
            - name: PUBSUB_SUBSCRIPTION
              value: "image-processing-queue-sub"
            - name: INTERACTION_POD_URL
              value: "http://interaction-service:8080"
            - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
              valueFrom:
                secretKeyRef:
                  name: pubsub-secret
                  key: GOOGLE_APPLICATION_CREDENTIALS_JSON